# Generated by Django 5.0 on 2024-01-04 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0007_labor_register_otp'),
        ('parties', '0003_task_delete_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='labor_id',
            field=models.ForeignKey(default='LB0001', on_delete=django.db.models.deletion.CASCADE, to='labor.labor_register'),
        ),
    ]
