# Generated by Django 5.0 on 2024-01-06 05:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0007_labor_register_otp'),
        ('parties', '0005_alter_task_labor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_installment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('payment_entry', models.FloatField(default=0)),
                ('paid_date', models.DateTimeField(default=datetime.date(2024, 1, 6))),
                ('labor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labor.labor_register')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
