# Generated by Django 5.0 on 2024-01-06 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0006_payment_installment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_installment',
            name='paid_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 11, 29, 57, 185021)),
        ),
    ]
