# Generated by Django 5.0 on 2024-01-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0008_alter_payment_installment_paid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='remaining_payment',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='paid_payment',
            field=models.FloatField(blank=True),
        ),
    ]
