# Generated by Django 5.0 on 2024-01-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0009_task_remaining_payment_alter_task_paid_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='paid_payment',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='remaining_payment',
            field=models.FloatField(blank=True),
        ),
    ]
