# Generated by Django 5.0 on 2023-12-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labor_register',
            name='id',
        ),
        migrations.AlterField(
            model_name='labor_register',
            name='labor_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
