# Generated by Django 5.0 on 2023-12-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0002_remove_labor_register_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labor_register',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='labor_register',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
