# Generated by Django 5.0 on 2023-12-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0003_labor_register_created_at_labor_register_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labor_register',
            name='labor_id',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False),
        ),
    ]
