# Generated by Django 5.0 on 2023-12-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0004_alter_labor_register_labor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labor_register',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
